project_id = "erghywhqrxmwqptusbxd"

[functions.generate-hr-document]
verify_jwt = true

[functions.verify-turnstile]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.qes-sign]
verify_jwt = true

[functions.qes-callback]
verify_jwt = false

[functions.hr-reminders]
verify_jwt = false

[functions.generate-reges-xml]
verify_jwt = true
