project_id = "erghywhqrxmwqptusbxd"

[functions.verify-turnstile]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.import-employees]
verify_jwt = true

[functions.sync-employees]
verify_jwt = true

[functions.delete-user]
verify_jwt = true
